# Site settings
title: SEO My Biz
email:
description: Supercharge your website with Search Engine Optimization> # this means to ignore newlines until "baseurl:"
baseurl: "/website/" # the subpath of your site, e.g. /blog/
url: "https://rustisaurusrex.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
